name: design-system-components release package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build
      - name: Copy package.json to dist
        run: cp package.json dist
      - name: Copy npmrc to dist
        run: cp .npmrc dist
      - name: cd to dist
        run: |
          cd dist
      - name: Publish to GitHub Packages
        run: |
          npm ci
          npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
